name: Run Sales Forecasting Notebook

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Jupyter notebook
        run: |
          pip install nbconvert
          jupyter nbconvert --to notebook --execute notebooks/sales_forecasting.ipynb --output executed_notebook.ipynb

